### ISSUE TITLE
harmonise $ and [[ usage?

### ISSUE THREAD

**Issue by cdriveraus** [ropensci/RefManageR#103]
I guess there are specific design considerations I'm unaware of here, but in trying to write what I thought was a fairly simple function for updating references automatically, I'm stuck with the issue that `myref$title` works fine but `myref[[field]]`, where `field <- 'title'`, does not. Is it possible to update specific fields without explicitly specifying the field as in `myref$title`?

**Comment by mwmclean** [comment]
Yes, this is currently possible via the `[<-` operator. You can view some examples with `help("[<-.BibEntry", package = "RefManageR")`. Here's another one:
```
library(RefManageR)
bfile <- system.file("Bib", "RJC.bib", package = "RefManageR")
bib <- ReadBib(bfile)
bib[[1]]
field <- "title"
new.value <- setNames("The New Title", field)
bib[1] <- new.value
bib[[1]]
```
Updating multiple entries and fields at once can be supported with lists:
```
fields1 <- c("year", "pages")
fields2 <- "journal"
new.values <- list(setNames(c("2024", ""), fields1), setNames("Bioinformatics", fields2))
bib[1:2] <- new.values
bib[[1]]
bib[[2]]
```
The `[[<-` operator is for updating entire entries at once, not just a subset of fields of the entry. If you're familiar with `do.call` you can also use `$<-` with your use case
```
bib <- do.call("$<-", list(bib, field, "The New Title"))
bib[[1]]
```

**Comment by cdriveraus** [comment]
Thanks, sorry for missing it in the docs :)
