### ISSUE TITLE
GetPubMedByID

### ISSUE THREAD

**Issue by rpietro** [ropensci/RefManageR#37]
Hi, I installed RefManageR through github using devtools, with no error messages. However, when I try to run 

    GetPubMedByID(c("11209037", "21245076"))

I get

    Error in GetPubMedByID(c("11209037", "21245076")) :  could not find function "GetPubMedByID"  

Also tried the installation through CRAN, still no error during the installation and the same error msg when I try the function above. any thoughts? thanks for the package, it's fantastic

**Comment by mwmclean** [comment]
How about `RefManageR::GetPubMedByID(c("11209037", "21245076"))`?

**Comment by rpietro** [comment]
thanks for the super fast response. here is the output:

   > RefManageR::GetPubMedByID(c("11209037", "21245076"))  
   Error in get(method, envir = home) :                    
     lazy-load database '/home/rpietro/R/x86_64-pc-linux-gnu-library/3.4/RefManageR/R/RefManageR.rdb' is corrupt   
     In addition: Warning messages:                          
     1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :                                          
        restarting interrupted promise evaluation             
     2: In get(method, envir = home) :                       
        restarting interrupted promise evaluation             
     3: In get(method, envir = home) : internal error -5 in R_decompress1    

some additional info that might be of help:

> R.Version()               
$platform                   
[1] "x86_64-pc-linux-gnu"   

$arch                       
[1] "x86_64"                

$os                         
[1] "linux-gnu"             

$system                     
[1] "x86_64, linux-gnu"     

$status                     
[1] ""                      

$major                      
[1] "3"                     

$minor                      
[1] "4.1"                   

$year                       
[1] "2017"                  

$month                      
[1] "06"                    

$day                        
[1] "30"                    

$`svn rev`                  
[1] "72865"                 

$language                   
[1] "R"                     

$version.string             
[1] "R version 3.4.1 (2017-06-30)"                      

$nickname                   
[1] "Single Candle"

**Comment by mwmclean** [comment]
Think this is related to [this](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16644) and [this](https://github.com/hadley/devtools/pull/1001).  I would first just try restarting R and reloading the package.  If that doesn't work I'd try using `remove.packages` and reinstalling.

**Comment by rpietro** [comment]
I had tried both steps above and it didn't work. I then removed R and reinstalled R and the package from github. Now it works. Thanks for your help
