### ISSUE TITLE
WriteBib.R does not write to stdout

### ISSUE THREAD

**Issue by splaisan** [ropensci/RefManageR#38]
When I do not set file, it sends the output to default references.bib instead of stdout
How can I modify WriteBib.R to allow stdout as output mode
maybe replace 'file' by 'fh' on line 45?
How can I test this, I have no experience in editing R packages
Thanks

**Comment by mwmclean** [comment]
Why do you need to use `WriteBib` at all for this?  Why aren't you just using the `print` method for `BibEntry` objects and base R functions?

**Comment by splaisan** [comment]
check ;-)
I changed this to 'writeLines(toBiblatex(bib, append = TRUE), fh)'
which supports either file or stdout()
but the fact remains that the code does not seem correct to me on [line 45](https://github.com/ropensci/RefManageR/blob/master/R/WriteBib.R).

Thanks
