### ISSUE TITLE
Print method does not match exactly

### ISSUE THREAD

**Issue by jvcasillas** [ropensci/RefManageR#41]
I have a .bib file with entries labeled in the following manner: ```r4ds_ch1```, ```r4ds_ch2```, ```r4ds_ch3```, etc. I use the following code to print the reference in a .Rmd file:

```
print(bib[key = "r4ds_ch2"], .opts = list(check.entries = TRUE, style = "latex", bib.style = "authoryear"))
```

The issue is that this prints every chapter that contains a bib key that is syntactically similar (i.e., r4ds_ch3, r4ds_ch4, etc.) when I only want to print one reference. Is this a bug? Or is there possibly an argument I haven't found yet that can limit the scope of what is printed so that it is an exact match?

**Comment by mwmclean** [comment]
I would try setting the option `use.regex` to `FALSE`.  It is difficult for me to help more than that without a reproducible example.
