### ISSUE TITLE
Include subset arguements in PrintBibliography

### ISSUE THREAD

**Issue by jvcasillas** [ropensci/RefManageR#45]
I would like to propose including arguments to the PrintBibliography function that allow for subsetting what is printed. I believe this will make it more useful for RMarkdown presentations. 

The issue, discussed [here](https://github.com/yihui/xaringan/issues/26), is that when using `RefManageR` with HTML slides, in this case `xaringan`, one often cites more authors than will fit in a single slide. I am not aware of a way around this issue. Do you have any suggestions?

To this end, I have made some adjustments to the `PrintBibliography` function that does this. You can find example slides [here](http://www.jvcasillas.com/xaringan_bib/index.html#1). I would like to request that something like this be implemented in `RefManageR` to make it fully functional with HTML presentations. My impression is that there is not currently a method of doing this so I have submitted a pull request.

**Comment by pat-s** [comment]
ping @mwmclean
