### ISSUE TITLE
Accept pubstate for Article instead of only year, date

### ISSUE THREAD

**Issue by bwiernik** [ropensci/RefManageR#50]
It's plausible that someone might include an in-press journal article in their bibliography. Such items might be represented in BibLaTeX as having a `pubstate` field instead of a `year` or `date` field. For example:
```
@article{Dahlkepsychmetapackagepsychometric,
  langid = {english},
  title = {{psychmeta}: An {{R}} Package for Psychometric Meta-Analysis},
  shorttitle = {Psychmeta},
  journaltitle = {Applied Psychological Measurement},
  shortjournal = {Appl. Psychol. Meas.},
  author = {Dahlke, Jeffrey A. and Wiernik, Brenton M.},
  pubstate = {in press}
}
```

Currently `ReadBib` discards such entries. Can it be modified to accept these values?

**Comment by mwmclean** [comment]
Yes, please see the vignette or documentation. Before the call to `ReadBib()` set the `check.entries` option to either `FALSE` or `"warn"`.  E.g. if your bib file is called mybib.bib, any of the following will work.

```
BibOptions(check.entries = FALSE)
ReadBIb(mybib.bib)
```
```
BibOptions(check.entries = "warn")
ReadBib(mybib.bib)
```
The `ReadBib` function also has a parameter `check`, that will allow you to read in the bib file, but you will receive errors when printing if you don't change the global option as above or pass the option to the print method.
```
bib <- ReadBib(mybib.bib, check = "warn")
```
```
bib <- ReadBib(mybib.bib, check = FALSE)
```
