### ISSUE TITLE
Required fields do not match bibtex requirements

### ISSUE THREAD

**Issue by robjhyndman** [ropensci/RefManageR#55]
A list of bibtex required fields and optional fields is given at http://bib-it.sourceforge.net/help/fieldsAndEntryTypes.php. These do not match the required fields of RefManageR. 

For example, a book should have a publisher, but RefManageR does not require it.

An inproceedings item does not require an editor, but RefManageR does require it.

**Comment by mwmclean** [comment]
The package checks to see if entries match the _BibLaTeX_ requirements see section 2.1 of the [BibLaTeX documentation](http://mirror.aarnet.edu.au/pub/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf).
