### ISSUE TITLE
Extraneous comma when max.names=1 

### ISSUE THREAD

**Issue by davidaknowles** [ropensci/RefManageR#56]
e.g. I would expect `Doe et al. (2011)` rather than `Doe, et al. (2011)`. 

Maybe this isn't standard outside my field though? 

Anyway, https://github.com/davidaknowles/refmanager has the changes. I can do a PR if there is consensus.

**Comment by vinhtantran** [comment]
The patch fixed the comma in the PrintBibliography() function but the comma is still present in the output of Cite()
