### ISSUE TITLE
extract title, author, etc without the brackets and the latex characters

### ISSUE THREAD

**Issue by bnicenboim** [ropensci/RefManageR#77]
Hi, nice package!

I haven't found a way to do this, so I guess this is a feature request.
When I do the following
```
bib <- ReadBib("allpubs.bib")
bib[1]$title
``` 
I get 
```
# [1] "{Response time models separate single- and dual-process accounts of memory-based decisions}"
```

I would like to find a way to get
```
# [1] "Response time models separate single- and dual-process accounts of memory-based decisions"
```

And the same for author, and other fields, and for the function  `as.data.frame`. 

Is there a hack I can use in the mean time?

**Comment by mwmclean** [comment]
My guess is that each entry field in the file is enclosed in an extra set of curly braces. If this is the case, the simplest work around is just to open `allpubs.bib` in any text editor and do two Find & Replace operations, one to replace "{{" with "{" and another to replace "}}" with "}". Equivalently, with R code, something like
```
bib <- readLines("allpubs.bib")
bib <- sub("{{", "{", bib, fixed = TRUE)
bib <- sub("}}", "}", bib, fixed = TRUE)
tfile <- tempfile()
writeLines(bib, tfile)
bib <- ReadBib(tfile)
```
should also work. If this doesn't work for you, please provide the file "allpubs.bib" or a minimal file reproducing the issue.

**Comment by bnicenboim** [comment]
Sorry for the lack of reprex, but here it is. The problem is not the double `{{`.

I see now that there are two issues.

Consider a bib file like this:

```
cat("
@article{soskuthy_when_2020,
	title = {When the tune shapes Morphology: {The} origins of vocatives in {English}},
	volume = {5},
	issn = {2058-458X},
	doi = {10/gg9nc2},
	number = {2},
	urldate = {2020-09-03},
	journal = {Journal of Language Evolution},
	author = {Sóskuthy, Márton and Roettger, Timo B},
	month = aug,
	year = {2020},
	pages = {140--155},
	customb={https://osf.io/ejr8m/}
}", file="temp.bib")
```
The title of the article using bib(la)tex will be translated into
`When the tune shapes morphology: The origins of vocatives in English`
or
`When the Tune Shapes Morphology: The Origins of Vocatives in English.`
depending on the csl style.

Notice that in the sentence case example,  the capitalization in "morphology" is removed, but the capitalization for words in curly brackets is kept. (And for title case, the {} can also force capitalization).

1. When I print the bib item, RefManageR doesn't enforce title or sentence case, but just removes the brackets.
```
library("RefManageR")
bib <- ReadBib("temp.bib")
bib[1]
[1] M. Sóskuthy and T. B. Roettger. “When the tune shapes Morphology:
The origins of vocatives in English”. In: _Journal of Language
Evolution_ 5.2 (aug. 2020), pp. 140-155. ISSN: 2058-458X. DOI:
10/gg9nc2. (Visited on 09/03/2020).
```
2. If I print the title I get that the `{` aren't removed as when I print the entire bib item.
```
bib[1]$title
[1] "When the tune shapes Morphology: {The} origins of vocatives in {English}"
```

I know I can remove the `{` afterwards, but  ideally I would like that both `bib[1]` and bib[1]$title gave me the same title.
