### ISSUE TITLE
Package archived on CRAN

### ISSUE THREAD

**Issue by antagomir** [ropensci/RefManageR#79]
This useful package is about to be removed from CRAN (orphaned). I can take over the maintenance at least for now, and see if it can be kept in CRAN.

If there are reasons for the orphaning it would be great to hear in order to avoid unnecessary work.

**Comment by mwmclean** [comment]
Where is this info that it's about to be orphaned? Why have I, the actual maintainer, who still actually maintains the package not been contacted? My email list on CRAN [here|https://cran.r-project.org/web/packages/RefManageR/index.html] still works and nobody's contacted me.

**Comment by antagomir** [comment]
It was CRAN standard announcement for reverse dependency maintainers after failure in emailing main author. Something gone wrong with the emails, good to hear that this is an active pkg.

**Comment by matmo** [comment]
The package has now been [archived on CRAN](https://cran.r-project.org/web/packages/RefManageR/index.html) due to a "policy violation", any news on why this has happened? This caused some other packages to be removed as well ([eurostat](https://cran.r-project.org/web/packages/RefManageR/index.html), for example).

**Comment by antagomir** [comment]
Hi! Is there more information on what policy violation this is?

Would be important to solve, we at eurostat pkg already started to receive
emails asking what is going on with the takedown.

If the policy violation is not mentioned in the error logs, I guess it
would be possible ask from CRAN admins directly?

Leo

**Comment by mwmclean** [comment]
Sorry everyone. There was an error in my fist attempt to move bibtex to Suggests. I was very surprised they would do this because I made clear to them the fix was very easy. I am confident the fix is sitting in master in this repo, just waiting for their confirmation/permission to submit it.

**Comment by antagomir** [comment]
Still not in CRAN - any updates?

**Comment by mwmclean** [comment]
I submitted on Friday, 30-Oct. They've thrown me in the [newbie queue|ftp://cran.r-project.org/incoming/newbies/], so the package is undergoing their manual check for first time submissions.

**Comment by mwmclean** [comment]
Back on CRAN as of 2020-11-13.
