### ISSUE TITLE
Custom bibliography styles for `BibEntry`

### ISSUE THREAD

**Issue by winniewytse** [ropensci/RefManageR#83]
Hello, I found that `BibEntry` supports up to 5 custom types for special bibliography styles (e.g., `bibtype = "CustomA"). Would you please explain how we could customize a new bibliography style such that `BibEntry` would read? Thank you!

**Comment by mwmclean** [comment]
I had to make a small code change to master to get this working. Please install it with `devtools::install_github("ROpensci/RefManageR")`. You will have to write your own code to specify how to format the custom bibtype as you'd like. You can start by inspecting how miscellaneous types are formatted by RefManageR's default style
```
library(RefManageR)
bib.env <- MakeBibLaTeX()
bib.env$formatMisc
```
For a custom bibtype called "Customa", define a new function in `bib.env` called `formatCustoma` containing your code and then register it using `tools::bibstyle()`
```
bib.env$formatCustoma <- function(paper) paste(paper$title, "(custom entry).")
tools::bibstyle("custom", bib.env)
```
Then tell RefManageR to use your custom bibliography style.
```
BibOptions(bib.style = "custom")
bib <- BibEntry(key = "a", bibtype = "Customa", title = "My custom work.")
bib
```
