### ISSUE TITLE
Take out "," before "et al.," when citing

### ISSUE THREAD

**Issue by RemiMahmoud** [ropensci/RefManageR#84]
Hi, 
 when I cite a reference with many authors names, I have the problem that a "," appears before the "et al.,"
 This seems to be related to the code of the function `Cite`:
 
`  if (length(authors) > max.names && !(first[i]  &&
                                                   longnamesfirst)){
                authors <- authors[seq_len(max.names)]
                authors[length(authors)] <- paste0(authors[length(authors)],
                                                   ", et al.")`

Is there a way to take out this "," ?

Thank you !

Rémi

**Comment by mwmclean** [comment]
I've removed the comma if you install the latest version of the package from GitHub `remotes::install_github("ropensci/RefManageR")`
