### ISSUE TITLE
Error due to key

### ISSUE THREAD

**Issue by graemeleehickey** [ropensci/RefManageR#86]
The following simple example leads to an error: `Error in vapply(unclass(x), attr, "", "key") : values must be length 1,
 but FUN(X[[98]]) result is length 3`.

```r
library(RefManageR)
pubs <- ReadPubMed("Hospital episode statistics[Title/Abstract]",
                   database = "PubMed",
                   field = "title/abstract",
                   retmax = 100)
```
I think it is having problems with one of the references. I have tried changing `retmax`, but it still leads to an error.

**Comment by graemeleehickey** [comment]
Hello ropensci,

I was wondering if you would be able to provide any insight to this bug, or perhaps a temporary workaround?

Thanks,
Graeme

**Comment by mwmclean** [comment]
Hi, thanks for reporting this bug. It is fixed now if you download and install the latest version of `RefManageR` from GitHub:
```
devtools::install_github("ropensci/RefManageR")
```

**Comment by graemeleehickey** [comment]
Thank you!
