### ISSUE TITLE
non-ascii character in inst/Bib/RJC.bib

### ISSUE THREAD

**Issue by GeoBosh** [ropensci/RefManageR#92]
I wonder if the following is on purpose - in file `inst/RJC.bib` the u-umlaut character in field journal of the reference with `idkey="carroll1976sequential"` and `title="On sequential density estimation"` seems to be in latin1.

**Comment by mwmclean** [comment]
Thanks for the report! I've removed the latin1 chars from that file in the latest release, which just reached CRAN.
